// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as IncButtonStyle$ProjectName from "./IncButtonStyle.bs.js";

function IncButton(Props) {
  var onClick = Props.onClick;
  var children = Props.children;
  return React.createElement("div", {
              className: IncButtonStyle$ProjectName.incButton,
              onClick: (function (param) {
                  return Curry._1(onClick, undefined);
                })
            }, children);
}

var make = IncButton;

export {
  make ,
  
}
/* react Not a pure module */
