// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@emotion/css";

var incButton = Css.css({
      display: "inline-block",
      padding: "5px 20px",
      backgroundColor: "#0063A5",
      color: "#fff",
      cursor: "pointer",
      userSelect: "none",
      borderRadius: "10px",
      "&:active": {
        opacity: "0.6"
      }
    });

export {
  incButton ,
  
}
/* incButton Not a pure module */
