// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Axios from "axios";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

var _axios = Axios.create({
      baseURL: "/api"
    });

function get(url) {
  return _axios.get(url).then(function (res) {
              if (res.status === 200) {
                return Promise.resolve(res.data);
              } else {
                return Promise.resolve(undefined);
              }
            });
}

function post(url, data, param) {
  if (data !== undefined) {
    return _axios.post(url, Caml_option.valFromOption(data)).then(function (res) {
                if (res.status === 200) {
                  return Promise.resolve(res.data);
                } else {
                  return Promise.resolve(undefined);
                }
              });
  } else {
    return _axios.post(url).then(function (res) {
                if (res.status === 200) {
                  return Promise.resolve(res.data);
                } else {
                  return Promise.resolve(undefined);
                }
              });
  }
}

export {
  _axios ,
  get ,
  post ,
  
}
/* _axios Not a pure module */
