// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as IncButton$ProjectName from "./components/IncButton.bs.js";

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement("div", undefined, match[0], React.createElement("br", undefined), React.createElement(IncButton$ProjectName.make, {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (v) {
                                    return v + 1 | 0;
                                  }));
                    }),
                  children: "inc"
                }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
