// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as App$ProjectName from "./App.bs.js";

var root = document.querySelector("#root");

if (root == null) {
  console.error("not find #root");
} else {
  ReactDom.render(React.createElement("div", undefined, React.createElement(App$ProjectName.make, {})), root);
}

var root$1 = (root == null) ? undefined : Caml_option.some(root);

export {
  root$1 as root,
  
}
/* root Not a pure module */
